### ISSUE TITLE
SQLite Driver issue Android

### ISSUE THREAD

**Issue by Mika571** [KinveyApps/Xamarin-Starter#1]
Running the application I get the following dialog on start. "Detected problems with app native libraries. libmonosgen-64bit-2.0.so: unauthorized access to "/system/lib64/libsqlite.so"

I think this is an error with the sqlite packages sqlite.net-pcl and sqlite.netcore-pcl. As a workaround I installed this [package ](https://www.nuget.org/packages/SQLite.Net.Platform.XamarinAndroidN) and referenced it in SQLite_Android.Getconnection()

**Comment by vinaygahlawat** [comment]
Thanks @Mika571 for the info and workaround!  This is an issue with our current SDK, and I will open a ticket for this.  I will update this issue when there is a fix available.

**Comment by vinaygahlawat** [comment]
Issue resolved with [dotnet-sdk #123](https://github.com/Kinvey/dotnet-sdk/pull/123) available in the `3.0.9` release. The `SQLite.Net.Platform.XamarinAndroidN` package has been added as a dependency in the SDK, and the app has been updated with `3.0.9`.

**Comment by etorsuarezm** [comment]
Do I have to do any changes at all?  Because I just updated to 3.0.9 and I'm still having this issue

**Comment by vinaygahlawat** [comment]
HI @etorsuarezm, thank you for your question.  I had to make some additional project changes to the Xamarin-Starter to support `3.0.9`, which I have just pushed.  Please pull the latest changes and try again, and let me know how it goes.
